#12 DB 베이스 수정
people-of-androido/chillaxing_cat pull request #13
Opened 2022-03-08 13:04 UTC by Gaegul2moja

- 기획 변경으로 인한 db 베이스 수정

2022-03-08 15:05 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +        internal fun fromDomainModel(dateModel: DateModel) : Holiday {
도메인 모델과의 변환은 엔터티에서 진행될 수 있도록 위치를 바꾸면 좋을 것 같습니다

2022-03-08 15:05 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/DayOffDao.kt
> +        internal fun fromDomainModel(dateModel: DateModel) : DayOff {
도메인 모델과의 변환은 엔터티에서 진행되도록 하면 좋겠네요.

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/LocalDatabase.kt
> +const val DB_VERSION = 5
끌어와섴ㅋㅋㅋ넵넵

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/DayOffDao.kt
> +        internal fun fromDomainModel(dateModel: DateModel) : DayOff {
그러게요 entity 쪽으로 옮기겠습니다 :)

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +interface HolidayDao {
넵 그러면 DayOff 쪽도 동일하게 추가해두겠습니다 (getDayOffWithPeriod)

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +    fun getHoliday(id: Int) : List<DateModel>
DayOff, Holiday 로 수정해두겠습니다

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +        internal fun fromDomainModel(dateModel: DateModel) : Holiday {
entity 로 옮겨두겠습니다

2022-03-08 15:13 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/entity/RestingTime.kt
> +    @ColumnInfo(name = "totalTime") val totalTime : String
기존 기조로 언더스코어로 바꿉시다

2022-03-08 15:18 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/RestingTimeDao.kt
> +    fun getRestingTime(id: Int) : List<RestingTimeModel>
모델로 되어있는 것은 도메인 레이어에서 한정해서 사용하는 것이 좋습니다.

2022-03-08 15:18 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/RestingTimeDao.kt
> +        internal fun fromDomainModel(restingTimeModel: RestingTimeModel): RestingTime {
DAO에서 데이터 변환을 하는것은 역할에 맞지 않아요.

2022-03-08 15:18 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/entity/RestingTime.kt
> +    @ColumnInfo(name = "totalTime") val totalTime : String
언더스코어로 하는것이 좋을것 같아요.

2022-03-08 15:31 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/MainMenuViewModel.kt
> +    fun dbTestAddRestingTime() {
이름에 db가 들어가는 것은 layer를 나누는 입장에서 좋지 않아보입니다.

2022-03-09 06:39 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/MainMenuViewModel.kt
> +    fun dbTestAddRestingTime() {
테스트 코드일 뿐이라서 일단 스킵하겠습니다

2022-03-09 09:45 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +interface HolidayDao {
@binsoopark Holiday의 경우 withPeriod 로 개발 시, 고려되어야할 부분들이 있을 것 같아, DayOffWithPeriod 만 진행하였습니다.
우선, 고려해야할 부분들은 아래와 같습니다.

1.  Holiday의 경우 달 별로 서버에 조회하는 것이기 때문에 period 가 만일 6달일 경우, 6번을 조회하게 됩니다.
2. 6달이 기간일 경우, db에 조회를 먼저 할 때 db에 일부인 3개월치의 데이터만 있을 경우 이를 존재한다고 해야할지 아니라고 해야할지가 모호합니다.
3. 만일 매번 서버에 조회할 경우, 자주 쓰이게될 메서드임에도 서버에 매번 조회하게 됩니다.
4. 달별로 db를 확인 후 각 달에 데이터가 없을 경우 달별로 서버를 찌르게되면 db, 서버를 총 12번 조회하게 됩니다...

해당 부분은 논의 후 추가해두겠습니다
검토 부탁드립니다 ( _ _ )

2022-03-11 16:24 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/dao/HolidayDao.kt
> +interface HolidayDao {
일단.. 기획에서 이야기 했던 것에 의하면 6달을 한번에 조회 요청할 케이스는 없을듯하고, 길어야 3개월일듯 합니다만. 3개월로 가정해도 효율적인 방법은 필요할 터이니, N개월이라고 가정하고 흐름을 이야기 해볼게요.

1. 달 별로 서버에 조회하는 것이라 N번 조회하게 되는 것은 Worst case인 경우가 되겠네요. 이 경우는 API 구조상 필연적이기 때문에 굳이 고민할 부분은 아닌듯 합니다.
2. 우선 DB에 기록을 한다고 했을 때, DB에 기록을 월 단위로 기록할 것인지 다른 단위로 기록할 것인지 결정이 필요합니다. 현재로서는 월 단위가 괜찮아보이긴 하네요. 제안이지만, 현재 스키마를 유지한다고 볼 때 아래의 규칙으로 작성하는 것이 어떨까 싶네요.
3. id -> "20220102" 와 같이 기록, name -> "공휴일이름" 이런식으로 기록을 하되, 대신 공휴일이 없는 달이 있을 수 있으니 이 경우에는 조회는 해왔지만, 없는 달도 기록한다고 가정하고 그 경우의 id는 만약 2022년 4월이라면, "20220400" 이런식으로 00으로 뒤에 채워주고, name에는 "NOTHING"과 같은 기록을 해 주는 것이죠. 그렇게 되면, 조회를 해 온 달은 반드시 1개 이상의 레코드가 기록이 된 상태가 되겠죠.
4. 만약 2022년 10월의 데이터를 조회해오고 싶다면, 202210으로 시작하는 id의 값을 조회하면 될 것이고, 2022년 10월~2022년12월의 데이터가 필요하다면, 202210, 202211, 202212로 시작하는 데이터를 각각 GROUP BY로 COUNT하여 있다면 사실상 이미 캐싱된 데이터가 맞으므로, API에서 조회할 필요가 없게 되죠. 이미 캐싱된 레코드가 있는지 판단하는 쿼리는 한번이면 충분하고, 그걸 로직으로 풀면 됩니다.(캐싱여부판단)
5. 그렇다면 어느 월부터 어느 월까지 DB에서 가져올 지, 어느 월은 API로 가져올 지 판단이 되기 때문에, DB에서 가져올 데이터는 그대로 가져오면 될 것이고(이 또한 1회면 조회됨), API에서 조회해서 가져올 데이터는 각 월마다 조회해서 가져오면 됩니다. 가져온 뒤에는 해당 데이터를 DB에 INSERT 시켜주면 되죠.(앞에서 언급했다시피 조회는 했으나 쉬는날이 하루도 없을 경우에는 NOTHING을 INSERT 해야겠죠)
6. 정리하면, 3달의 데이터를 예를 들자면, WORST는 캐싱여부 판단 1회 + API에서 조회 3회가 필요하게 되며, BEST는 캐싱여부 판단 1회 + DB 쿼리 1회로 2회가 필요하게 되겠네요. 섞여있다면, 캐싱여부 판단 1회 + 쿼리조회 1회 + API 조회 1회 혹은 2회 정도가 되구요. 아무리 많아도 4회면 됩니다.
7. 마지막으로 여기에서 INSERT는 제외시켰지만, API 1회 조회당 INSERT 1회씩은 자동으로 붙는다고 보면 됩니다. 혹은 한번에 INSERT한다면 API 몇번을 조회하든 INSERT는 1회가 되겠네요.

위 로직을 한번 천천히 이해해보고 이해가 된다면 좋겠고, 혹시 이해가 잘 안간다면, 리플이나 따로 연락줘도 되요!

2022-03-11 16:28 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/domain/usecase/GetHoliday.kt
> +    suspend operator fun invoke(id: Int) = holidayRepository.getHoliday(id)
좋습니다.ㅎ 구체적인 방식은 위에 별도의 댓글에서 언급했습니다~

2022-03-15 13:47 UTC, binsoopark requested changes

2022-03-15 13:47 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/HolidayRepositoryImpl.kt
> +    private val authKey = "H4x622Qm0l4CRmP3aW++k0EZw++gIW0xnawVEKxNDWCKRg8HjZjyyQQnrEn8cToDhZkHiHxYDkvAAcMOohqbbA=="
이 값은... BuildConfig에 값을 넣고 그 값을 참조하게 하는 방식으로 하면 좋을 것 같습니다. build.gradle에서 값을 설정해서 불러오는 방식으로 구현하면 됩니다.

2022-03-19 13:00 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/DayOffRepositoryImpl.kt
> +                failMessage = e.message!!
suspendCoroutine 부분을 제거하여, 해당 부분은 삭제하였는데,
혹시 try catch 는 유지하는 것이 db 조회 시 에러를 잡는데 도움이 되는걸까요?
![image](https://user-images.githubusercontent.com/38804451/159122068-43c7422d-c23f-4ebf-91bf-a68b887d6fbb.png)

2022-03-19 13:00 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/DayOffRepositoryImpl.kt
> +                failMessage = e.message!!
위와 동일합니다

2022-03-19 13:12 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/HolidayRepositoryImpl.kt
> +    private val authKey = "H4x622Qm0l4CRmP3aW++k0EZw++gIW0xnawVEKxNDWCKRg8HjZjyyQQnrEn8cToDhZkHiHxYDkvAAcMOohqbbA=="
위와 동일합니다 :)

2022-03-19 13:12 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/HolidayRepositoryImpl.kt
> +    private val authKey = "H4x622Qm0l4CRmP3aW++k0EZw++gIW0xnawVEKxNDWCKRg8HjZjyyQQnrEn8cToDhZkHiHxYDkvAAcMOohqbbA=="
그렇게 수정해 두었습니다! 이렇게도 하는군요

2022-03-19 13:40 UTC, binsoopark approved these changes

2022-03-19 13:40 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/DayOffRepositoryImpl.kt
> +        val result : Boolean = suspendCoroutine { cont ->
수정확인했습니다

2022-03-19 13:41 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/DayOffRepositoryImpl.kt
> +                failMessage = e.message!!
잘 수정된것 확인했습니다~

2022-03-19 13:47 UTC, merged

2022-03-19 13:52 UTC, binsoopark commented
수고 많았습니다.ㅎㅎㅎ 이번 PR은 베이스 PR이라 좀 더 격려를!!!