Feature/8 gaegul2moja setting and push development
people-of-androido/chillaxing_cat pull request #15
Opened 2022-04-02 09:09 UTC by Gaegul2moja

중간 PR 올립니다 :)
- 로컬 저장 방식 수정
- conflict 내용 수정
- 로컬 저장 데이터 추가
- 다이얼로그 추가

2022-04-02 09:09 UTC, Gaegul2moja commented
@binsoopark 중간 pr 올렸는데 확인 부탁드립니다 :)

2022-04-02 14:16 UTC, binsoopark requested changes
string관련 코멘트는 일부만 기록했지만 전반적으로 안된 부분들 다 반영했으면 좋겠습니다.
일단 지금 코멘트한 부분들 체크해주시고, 다음 작업을 위해 빠른 merge 될 수 있도록 합시다.ㅎ

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +            Toast.makeText(getApplication(), "저장이 완료되었습니다 :)", Toast.LENGTH_SHORT).show()
문자열은 string.xml에서 처리될 수 있도록 해주세요~

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/proto/settings.proto
> +  bool push_available = 1;
"푸시가 이용 가능한가" 라는 뜻을 담고 있는 것인가요? 의미상 알림을 활성화 시킬것이가 라는 뜻으로 보았었는데 어떤 의미가 맞을지 확인해주면 좋을것 같습니다.

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/proto/settings.proto
> +  int32 goal_resting_time_hour = 4;
hour와 minute는 하나로 묶어서 처리해도 될 것 같습니다.
string으로 4자리 숫자로 처리해도 될 것 같고, timestamp로 변환한다면 int32로 해도 될것 같기도 합니다.
실제로 viewmodel이나 view에서는 나눠서 처리가 되겠지만, 그것을 data layer에서 일치시키지 않아도 됩니다. 오히려 이 부분은 따로 떼어서 관리하는 부분이 아니고 나눌 경우 이점이 따로 없을듯 하니 합치는걸 제안합니다.

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/res/layout/dialog_initial_setting.xml
> +                    android:text="출근 시간"
string.xml에서 처리하는 것이 좋을 것 같습니다~

2022-04-02 14:16 UTC, binsoopark commented on app/build.gradle
> +    implementation "androidx.datastore:datastore-preferences:1.0.0"
preference datastore를 이용하지 않는 것으로 변경하였으니, 이 부분은 불필요해 보입니다.

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/ChillaxingCatApplication.kt
> +internal val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")
preference datastore를 쓰지 않을 것이므로 제거해도 될것 같습니다.

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/ChillaxingCatApplication.kt
> +internal var notificationManager: NotificationManager? = null
notificationManager와 alarmManager는 인스턴스를 유지할 필요는 없어보이니 굳이 이곳에서 선언해서 사용하지 않아도 될 것 같습니다. 검토해보고 그래도 필요할 경우 DI를 이용하여 관리될 수 있도록 별도의 클래스로 정의해서 사용하는 것이 좋을 것 같습니다.

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/MainActivity.kt
> +        notificationManager = getSystemService(NOTIFICATION_SERVICE) as NotificationManager?
이 부분들은 따로 할당만 하고 사용하지는 않은것 같은데 불필요한 분은 아닌지 확인해주세요~

2022-04-02 14:16 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/ui/MainMenuFragment.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
super만 호출한다면, 굳이 override가 필요하지 않아보입니다.

2022-04-03 16:27 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/AlarmReceiver.kt
> +            .setContentTitle("퇴근할 시간이다냥..!!") // 제목
일괄 수정하였습니다 :)

2022-04-03 16:28 UTC, Gaegul2moja commented on app/build.gradle
> +    implementation "androidx.datastore:datastore-preferences:1.0.0"
삭제하였습니다 :)

2022-04-03 16:28 UTC, Gaegul2moja commented on app/src/main/res/layout/dialog_initial_setting.xml
> +                    android:text="출근 시간"
일괄 수정하였습니다 :)

2022-04-03 16:29 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/ChillaxingCatApplication.kt
> +internal val Context.dataStore: DataStore<Preferences> by preferencesDataStore(name = "settings")
삭제하였습니다 :)

2022-04-03 16:30 UTC, Gaegul2moja commented on app/src/main/proto/settings.proto
> +  int32 goal_resting_time_hour = 4;
: 를 구분자로 사용하여 string 으로 변경하였습니다

2022-04-03 16:52 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/ChillaxingCatApplication.kt
> +internal var notificationManager: NotificationManager? = null
이해를 잘못하고 있었더라구요 각 사용처 쪽의 멤버변수로 이동하였습니다 :)

2022-04-03 16:52 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/MainActivity.kt
> +        notificationManager = getSystemService(NOTIFICATION_SERVICE) as NotificationManager?
위와 동일합니다 :)

2022-04-03 17:06 UTC, Gaegul2moja commented
@binsoopark 추가 수정하였습니다 참고 부탁드립니다 :)

2022-04-03 23:20 UTC, binsoopark commented on app/src/main/proto/settings.proto
> +  bool push_enabled = 1;
앞서 질문을 남긴 부분인데요. 답이 따로 달려있지는 않아서 다시 남겨보자면, 이 기능 관련해서는 '푸시' 보다는 '알림'혹은 '알람'이 맞는 부분이라고 생각되는데요. 실제로 우리가 푸시를 보내고 수신하는 부분에 해당하지는 않기 때문에, 어떻게 생각하는지 궁금합니다.

2022-04-03 23:38 UTC, binsoopark requested changes

2022-04-03 23:38 UTC, binsoopark commented on app/src/main/proto/settings.proto
> +  bool is_app_first_launched = 5;
is는 보통 method 단계에서 사용하기 때문에, 값이나 키에서 사용하는 이름으로는 flag나 다른 이름이 좋을 것 같습니다. 또한 초기 실행이 되었는지 여부를 저장하는 키가 필요한지 여부에 대해서는 필요성에 대해서 고민이 필요할 것 같습니다.(만약 A,B,C 값이 설정되었을 때 추가로 설정하지 않기를 원해서라면, 해당 값으로 판단하는 것이 좋을 수 있습니다.)

2022-04-03 23:38 UTC, binsoopark commented on app/src/main/res/layout/dialog_cat_job.xml
> +                android:text="직업 선택"
한글로 들어간 이 부분은 string resource 처리가 필요할 것 같습니다. 이를 비롯한 몇 군데는 아직 변환이 덜 반영된 것으로 보입니다.

2022-04-03 23:38 UTC, binsoopark commented on app/src/main/res/values/themes.xml
> +
불필요한 빈 줄로 보입니다.

2022-04-03 23:38 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +            Toast.makeText(getApplication(), "저장이 완료되었습니다 :)", Toast.LENGTH_SHORT).show()
이러한 부분도 string resource 반영이 되면 좋을 것 같습니다.

2022-04-03 23:38 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/SettingsRepositoryImpl.kt
> +    override suspend fun getIsAppFirstLaunched(): Flow<Boolean> = settingsDataStore.isAppFirstLaunchedFlow
is에 get을 결합한 형태는 기계적인 결합같아보입니다. is만으로도 충분히 동사 표현이 가능합니다.

2022-04-04 14:03 UTC, Gaegul2moja commented on app/src/main/res/layout/dialog_cat_job.xml
> +                android:text="직업 선택"
해당 다이얼로그 쪽은 없애는게 맞을지 확실치 않아서 우선적으로 삭제가 보류된 상태입니다 내일 기획 관련 얘기가 필요할 것 같습니다

2022-04-05 11:47 UTC, Gaegul2moja commented on app/src/main/proto/settings.proto
> +  bool push_enabled = 1;
push : 서버에서 알림을 준 것
notification : 알림

2022-04-05 11:52 UTC, Gaegul2moja commented on app/src/main/proto/settings.proto
> +  bool is_app_first_launched = 5;
is_app_first_launched 관련 usecase 등 삭제

2022-04-05 11:53 UTC, Gaegul2moja commented on app/src/main/res/values/themes.xml
> +
삭제 필요

2022-04-05 11:54 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +            Toast.makeText(getApplication(), "저장이 완료되었습니다 :)", Toast.LENGTH_SHORT).show()
빼야함

2022-04-05 11:57 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/data/repository/SettingsRepositoryImpl.kt
> +    override suspend fun getIsAppFirstLaunched(): Flow<Boolean> = settingsDataStore.isAppFirstLaunchedFlow
삭제 예정 Usecase 쪽은 남겨서 checkAppFirstLaunched 로 만들어서 사용해야함

2022-04-06 11:48 UTC, Gaegul2moja commented
@binsoopark 피드백 반영되었습니다 :)

2022-04-06 16:23 UTC, binsoopark requested changes

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +                if (it.isNotEmpty() && it.contains(":")) {
```suggestion
        val regex = Regex("[0-2][0-9][:][0-5][0-9]")
	if (regex.matchEntire(it)?.groupValues?.size?:0 > 0) {
```

문제는 없으나.. 좀 더 개선해보자면 이 코드는 어떨지 제안해봅니다.ㅎ

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +    private fun storePushSetting(getPush : Boolean) {
아직 이곳의 이름들은 push가 남아있네요.

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +        if (calendar.time < Date()) {
이 if문은 바로 위의 apply 안에 들어가도 되지 않을까요? 별도로 나와있는 이유를 잘 모르겠어요~

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +                Integer.parseInt(goalRestingTimeHour.value) >= 0 &&
Int 형 변환할때 kotlin이니 "string".toInt() 를 사용하는게 좋을 것 같습니다.
그리고 Integer.parseInt()와 "".toInt() 둘 다 마찬가지로 NumberFormatException이 발생할 수 있으니 이걸 구현하지 않고 회피하려면 "".toIntOrNull() ?: -1 과 같이 변환하는게 좋을 것 같아요. null 처리하면 0하고 비교가 안되니 -1로 반영한 거에요.

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/res/layout/fragment_setting.xml
> +                android:text="사용자 설정 정보 수정"
string을 resource로 변환하는 부분이 누락된 것 같네요.

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/res/layout/fragment_user_setting.xml
> +                    android:text="수정하기" />
이 부분도 string이 resource로 변환하는 것이 누락된 것 같아요.

2022-04-06 16:23 UTC, binsoopark commented on app/src/main/proto/settings.proto
> +  string goal_resting_time = 4;
이건.. 참고하면 될 것 같은데.
캘린더에서 연관된 다음 부분을 구현하다보니, 우리가 사실 쉬다 라는 개념이 resting이 아닌 chillaxing이라고 워딩을 잡고 가고 있어요. 그래서 쉰다 = chillaxing이 되는게 맞다고 생각이 들고, 수정하는게 좋아보이긴 하는데,
이 부분 관련해서는 수정 포인트가 많으니 일단은 무리가 되면 놔두고 merge를 진행해도 되요(제가 수정해도 되니)
일단 의견을 말은 해야 할 것 같아서 남겨요.

2022-04-06 16:24 UTC, binsoopark commented
추가 커밋 확인했는데, 저 역시 추가로 보다보니 보이는게 있어서 코멘트 추가했습니다~

2022-04-07 14:09 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/domain/usecase/GetIsAppFirstLaunched.kt
> +            resultHandler.handleSuccess(result.first().isEmpty())
이거는 그때 카페에서 말하기도 했었는데, 향후 필수인 값이 goalRestingTime 외에도 있을 가능성이 있어서 따로 있는 것이 의미 있다고 판단했습니다. 그리고, repository.getReminderText()의 값, repository.getReminderTime()의 값의 경우는 푸시를 필수로 설정 하지 않을 수 있기 때문에 필수 값이 아닙니다 :)
그래서 일단 피드백 수정 사항으로는 GetIsAppFirstLaunched 의 네이밍을 checkRequiredValues 등으로 바꿔서 수정하겠습니다 👍

2022-04-07 14:16 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/di/UseCaseModule.kt
> +    single { GetIsAppFirstLaunched(get(), get()) }
맞네요 필수 설정 값이 정상 입력되었는지의 판단이라고 생각되어서 isRequiredValuesEntered 로 수정하였습니다!

2022-04-07 14:27 UTC, Gaegul2moja commented on app/src/main/java/com/peopleofandroido/chillaxingcat/presentation/viewmodel/UserSettingViewModel.kt
> +                Integer.parseInt(goalRestingTimeHour.value) >= 0 &&
![image](https://user-images.githubusercontent.com/38804451/162222472-298ae18c-2c36-43eb-9d64-4899cc03066c.png)
이렇게 넣었는데 맞을까요..? -1 이 0보다 작으니까 조건에 맞지 않게 하는 이치라면 12보다 큰 값을 넣는게 맞아보여서 이렇게 작성했지만 -1은 그럴 수 있을 것 같은데 특정 값을 이렇게 넣는 것이 애매한듯하여서 MAX VALUE 로 넣어버렸습니다

2022-04-07 15:27 UTC, binsoopark approved these changes
확인했습니다. 일부 수정이 조금 더 필요한것과 무플이 일부 있기는 하지만..흑.
진행해도 큰 지장은 없을것같아요~

2022-04-07 15:32 UTC, merged